version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: test/
      linters:
        - errcheck
